# Use precise (trusty missing help2man)
#  https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-trusty
dist: precise
#
# C includes autotools and make by default
language: c
#
# Extra packages
addons:
  apt:
    packages:
    - help2man
#
# Run
script:
 # Run the commit hooks before building
 - git diff 4b825dc642cb6eb9a060e54bf8d69288fbee4904 | ./packaging/check-files -
 # Build the packaged tar file, then the final files and run any tests we can
 - fakeroot ./packaging/git-build && ./configure && make check
